### ISSUE TITLE
Ranking não está considerando critérios de desempate

### ISSUE THREAD

**Issue by rafaelcoutinho** [rafaelcoutinho/northapp#124]
![uploads/b553ad25-7436-4ef4-9b34-6a7052618f8b/WhatsApp-Image-20160505 (1).jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb553ad25-7436-4ef4-9b34-6a7052618f8b%2FWhatsApp-Image-20160505+%281%29.jpg)

![uploads/4cc73c21-9092-46be-b31e-e62a9862b2be/WhatsApp-Image-20160505.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4cc73c21-9092-46be-b31e-e62a9862b2be%2FWhatsApp-Image-20160505.jpg)

**Comment by rafaelcoutinho** [comment]
@wilsonhirai Aparentemente tem equipes que estão totalmente empatadas.
Comparei suas melhores posicoes, qtde de vezes e numero de participacoes.
Elas são:
Realmente empatados Os Lerdinhos e Limonautas 
Realmente empatados Engenheiros Da Mata 2 e Torresmo com Cachaça
Realmente empatados Mercenárias e Mula Com Cabeça
Realmente empatados Dick Vigarista e Véi, Na Boa!
Realmente empatados Pow Man e Rosa Dos Ventos 
Realmente empatados #vempratrilha e Os Pé De Figo 
Realmente empatados Los Coyotes - Studio Welt e Não Empurra Que é Pior
Realmente empatados Torresminho e Só Vô Si Xô Vê
Realmente empatados Vikings e Pururuca

Você pode confirmar isso?

**Comment by rafaelcoutinho** [comment]
Subi a versão corrigida para Android

**Comment by wilsonhirai** [comment]
@rafaelcoutinho no caso das equipes acima, vai ficar por ordem alfabética mesmo. Elas participaram apenas 1 vez, então não dá pra ter desempate. O correto seria avaliar a ficha de performance para desempatar... mas não compensa fazer isso, equipes que estão na parte de baixo da tabela de classificação não vão reclamar por isso. O problema são os primeiros, que vão conferir se está correto, pois podem ganhar troféu ou não com o desempate.

**Comment by wilsonhirai** [comment]
Valeu Rafael!

Desculpe por não conseguir fazer antes as coisas que vc me pediu..

Aqui na North não temos horário fixo de trabalho, ontem tivemos a checagem da copa north e não fiquei no escritório.

Hoje também entrei só na parte da tarde, então só consegui fazer agora..

 

 

Qualquer dúvida estou à disposição.

Obrigado e abraços.

 


	
		
 





Wilson Hirai         
Northbrasil Treinamento e Desenvolvimento

tel: <tel:+55%2019%203289%205281> +55 19 3289 5281 | cel: <tel:+55%2019%2098142%206043> +55 19 98142 6043

 <mailto:logistica@northbrasil.com.br> logistica@northbrasil.com.br |  <http://www.northbrasil.com.br/> www.northbrasil.com.br 

av albino j b de oliveira, 2027 | campinas/sp

 

 <http://facebook.com/northbrasilconsultoria>   <http://us.linkedin.com/in/northbrasil>   <http://twitter.com/northbrasil_ted>   <http://instagram.com/northbrasil> 



“Atividades vivenciais centradas no participante, focadas em performance.”

 

De: Rafael Coutinho [mailto:notifications@github.com] 
Enviada em: sábado, 7 de maio de 2016 12:59
Para: rafaelcoutinho/northapp
Assunto: Re: [rafaelcoutinho/northapp] Ranking não está considerando critérios de desempate (#124)

 

Subi a versão corrigida para Android

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub <https://github.com/rafaelcoutinho/northapp/issues/124#issuecomment-217646828>   <https://github.com/notifications/beacon/AQJ1VfBCXesOkUjCxDYSSPgtZ_jYZKaiks5p_La4gaJpZM4IZcwq.gif> 



---
Este email foi escaneado pelo Avast antivírus.
https://www.avast.com/antivirus
